INSERT INTO provinces(id,province) VALUES (1,'Bali');
INSERT INTO provinces(id,province) VALUES (2,'Bangka Belitung');
INSERT INTO provinces(id,province) VALUES (3,'Banten');
INSERT INTO provinces(id,province) VALUES (4,'Bengkulu');
INSERT INTO provinces(id,province) VALUES (5,'DI Yogyakarta');
INSERT INTO provinces(id,province) VALUES (6,'DKI Jakarta');
INSERT INTO provinces(id,province) VALUES (7,'Gorontalo');
INSERT INTO provinces(id,province) VALUES (8,'Jambi');
INSERT INTO provinces(id,province) VALUES (9,'Jawa Barat');
INSERT INTO provinces(id,province) VALUES (10,'Jawa Tengah');
INSERT INTO provinces(id,province) VALUES (11,'Jawa Timur');
INSERT INTO provinces(id,province) VALUES (12,'Kalimantan Barat');
INSERT INTO provinces(id,province) VALUES (13,'Kalimantan Selatan');
INSERT INTO provinces(id,province) VALUES (14,'Kalimantan Tengah');
INSERT INTO provinces(id,province) VALUES (15,'Kalimantan Timur');
INSERT INTO provinces(id,province) VALUES (16,'Kalimantan Utara');
INSERT INTO provinces(id,province) VALUES (17,'Kepulauan Riau');
INSERT INTO provinces(id,province) VALUES (18,'Lampung');
INSERT INTO provinces(id,province) VALUES (19,'Maluku');
INSERT INTO provinces(id,province) VALUES (20,'Maluku Utara');
INSERT INTO provinces(id,province) VALUES (21,'Nanggroe Aceh Darussalam (NAD)');
INSERT INTO provinces(id,province) VALUES (22,'Nusa Tenggara Barat (NTB)');
INSERT INTO provinces(id,province) VALUES (23,'Nusa Tenggara Timur (NTT)');
INSERT INTO provinces(id,province) VALUES (24,'Papua');
INSERT INTO provinces(id,province) VALUES (25,'Papua Barat');
INSERT INTO provinces(id,province) VALUES (26,'Riau');
INSERT INTO provinces(id,province) VALUES (27,'Sulawesi Barat');
INSERT INTO provinces(id,province) VALUES (28,'Sulawesi Selatan');
INSERT INTO provinces(id,province) VALUES (29,'Sulawesi Tengah');
INSERT INTO provinces(id,province) VALUES (30,'Sulawesi Tenggara');
INSERT INTO provinces(id,province) VALUES (31,'Sulawesi Utara');
INSERT INTO provinces(id,province) VALUES (32,'Sumatera Barat');
INSERT INTO provinces(id,province) VALUES (33,'Sumatera Selatan');
INSERT INTO provinces(id,province) VALUES (34,'Sumatera Utara');
